/**
 * Asset Manifest Types
 *
 * The manifest is a JSON document shipped alongside every experience that
 * lists all required assets with checksums and compression hints. The
 * Viewer uses it to:
 *   - Prefetch critical assets
 *   - Verify integrity (SHA-256)
 *   - Decide which decoders to initialize
 *
 * Generated by `scripts/build-manifest.ts`. Validated by `lib/3d/manifest.ts`.
 */

import type { CompressionHints } from './useCompressedAsset';

export interface ManifestAsset {
  /** Public URL of the asset (CDN-served). */
  url: string;
  /** Logical name (e.g. "exterior.glb", "lobby-pano.jpg"). */
  name: string;
  /** Asset kind. */
  kind: 'glb' | 'splat' | 'panorama' | 'usdz' | 'hdr' | 'texture';
  /** Size in bytes. */
  size: number;
  /** SHA-256 of the asset bytes (lowercase hex). */
  sha256: string;
  /** Compression hints (server-side compressed assets). */
  compression: CompressionHints;
  /** Logical grouping for preloading (e.g. "scene", "ui"). */
  group: string;
  /** Whether this is critical for first paint. */
  critical: boolean;
}

export interface AssetManifest {
  /** Manifest schema version. Bump on breaking changes. */
  version: 1;
  /** ISO 8601 timestamp of when the manifest was generated. */
  generatedAt: string;
  /** Project this manifest belongs to. */
  projectId: string;
  /** Experience within the project. */
  experienceId: string;
  /** List of assets. */
  assets: ManifestAsset[];
}

/**
 * Validate a manifest object. Returns an array of error messages; empty
 * array means the manifest is valid. Used by `__tests__` and by the
 * Viewer at boot to fail fast on a broken build.
 */
export function validateManifest(input: unknown): string[] {
  const errors: string[] = [];
  if (!input || typeof input !== 'object') {
    return ['manifest is not an object'];
  }
  const m = input as Partial<AssetManifest>;
  if (m.version !== 1) errors.push(`unsupported manifest version: ${m.version}`);
  if (typeof m.generatedAt !== 'string') errors.push('missing generatedAt');
  if (typeof m.projectId !== 'string') errors.push('missing projectId');
  if (typeof m.experienceId !== 'string') errors.push('missing experienceId');
  if (!Array.isArray(m.assets)) {
    errors.push('assets must be an array');
    return errors;
  }
  m.assets.forEach((a, i) => {
    if (!a || typeof a !== 'object') {
      errors.push(`assets[${i}] is not an object`);
      return;
    }
    if (typeof a.url !== 'string') errors.push(`assets[${i}].url missing`);
    if (typeof a.name !== 'string') errors.push(`assets[${i}].name missing`);
    if (typeof a.size !== 'number' || a.size < 0) errors.push(`assets[${i}].size invalid`);
    if (typeof a.sha256 !== 'string' || !/^[a-f0-9]{64}$/.test(a.sha256))
      errors.push(`assets[${i}].sha256 invalid (expected 64 hex chars)`);
    if (!a.compression || typeof a.compression !== 'object')
      errors.push(`assets[${i}].compression missing`);
  });
  return errors;
}

/** Group assets by their `group` field — used for staged preloading. */
export function groupManifestAssets(manifest: AssetManifest): Record<string, ManifestAsset[]> {
  const out: Record<string, ManifestAsset[]> = {};
  for (const a of manifest.assets) {
    (out[a.group] ??= []).push(a);
  }
  return out;
}

/** Pick out the critical assets that should be loaded first. */
export function criticalAssets(manifest: AssetManifest): ManifestAsset[] {
  return manifest.assets.filter((a) => a.critical);
}
